import type { IconName } from "./components/Icon";

export const AppIcon = {
  Home: "home" as IconName,
  HomeFilled: "home-filled" as IconName,
  Procesos: "git-network" as IconName,
  ProcesosFilled: "git-network" as IconName,
  Ot: "construct" as IconName,
  OtFilled: "construct" as IconName,
  Calendario: "calendar" as IconName,
  CalendarioFilled: "calendar-filled" as IconName,
  Reportes: "bar-chart" as IconName,
  ReportesFilled: "bar-chart-filled" as IconName,
  Configuracion: "settings" as IconName,
  ConfiguracionFilled: "settings-filled" as IconName,
  Inspeccion: "clipboard" as IconName,
  InspeccionFilled: "clipboard-filled" as IconName,
  Checklist: "checklist" as IconName,
  ChecklistFilled: "checklist-filled" as IconName,
  Farm: "farm-filled" as IconName,
  Barn: "barn-filled" as IconName,
  Users: "people" as IconName,
  UsersFilled: "people-filled" as IconName,
  Templates: "document-text" as IconName,
  TemplatesFilled: "document-text-filled" as IconName,
  Logout: "log-out" as IconName,
  Add: "add" as IconName,
  Pencil: "pencil" as IconName,
  Trash: "trash" as IconName,
  Search: "search" as IconName,
  Menu: "menu" as IconName,
  Close: "close" as IconName,
  Check: "checkmark" as IconName,
  Bell: "notifications" as IconName,
  Info: "information-circle" as IconName,
  Alert: "alert-circle" as IconName,
  Chat: "chatbubble" as IconName,
  Camera: "camera" as IconName,
  Time: "time" as IconName,
  Analytics: "analytics" as IconName,
  Palette: "palette" as IconName,
  ChevronForward: "chevron-forward" as IconName,
} as const;
