import { neutrals, brand, success, warning, danger } from "../basePalette";
import { accent, cta1, cta1Contrast } from "../colors";
import type { SemanticColors } from "../semanticColors";

export const darkColors: SemanticColors = {
  text: {
    heading: neutrals.N50,
    body: neutrals.N100,
    caption: neutrals.N400,
    brand: brand.M400,
    subtle: neutrals.N400,
    subtlest: neutrals.N600,
    disabled: neutrals.N600,
    success: success.S400,
    successMid: success.S500,
    successContrast: success.S600,
    warning: warning.W400,
    warningMid: warning.W500,
    warningContrast: warning.W600,
    danger: danger.D400,
    dangerContrast: danger.D500,
    linkDefault: brand.M400,
    linkHover: brand.M300,
    linkPressed: brand.M200,
    negative: danger.D400,
  },
  icon: {
    default: neutrals.N400,
    brand: brand.M400,
    subtle: neutrals.N500,
    subtlest: neutrals.N600,
    disabled: neutrals.N600,
    success: success.S400,
    successMid: success.S500,
    successContrast: success.S600,
    warning: warning.W400,
    warningMid: warning.W500,
    warningContrast: warning.W600,
    danger: danger.D400,
    dangerContrast: danger.D500,
    linkDefault: brand.M400,
    linkHover: brand.M300,
    linkPressed: brand.M200,
    negative: danger.D400,
  },
  border: {
    default: neutrals.N700,
    subtle: neutrals.N600,
    subtlest: neutrals.N800,
    light: neutrals.N700,
    lightest: neutrals.N800,
    brand: brand.M500,
    brandLight: brand.M400,
    brandLighter: brand.M300,
    brandContrast: brand.M200,
    focus: brand.M400,
    error: danger.D400,
    success: success.S400,
    warning: warning.W400,
    danger: danger.D400,
  },
  surface: {
    pageDefault: neutrals.N950,
    pageSubtlest: neutrals.N900,
    pageSubtle: neutrals.N800,
    card: neutrals.N800,
    cardBorder: neutrals.N700,
    brand: brand.M500,
    brandSubtle: brand.M700,
    brandSubtler: brand.M800,
    brandSubtlest: brand.M900,
    success: success.S400,
    successSubtle: success.S800,
    warning: warning.W400,
    warningSubtle: warning.W800,
    danger: danger.D400,
    dangerSubtle: danger.D800,
    overlay: neutrals.N950,
    modal: neutrals.N900,
  },
  components: {
    // Sidebar = misma superficie de marca en ambos modos (accent). Item activo = CTA1.
    sidebar: {
      background: accent.background,
      hover: "rgba(255, 255, 255, 0.06)",
      activeBackground: cta1,
      activeText: cta1Contrast,
      text: accent.text.secondary,
      sectionTitle: accent.text.secondary,
      title: accent.text.primary,
    },
    button: {
      primaryBg: brand.M500,
      primaryText: neutrals.N0,
      primaryHover: brand.M400,
      primaryPressed: brand.M300,
      primaryDisabled: neutrals.N700,
      secondaryBg: neutrals.N800,
      secondaryText: brand.M300,
      secondaryBorder: brand.M500,
      secondaryHover: neutrals.N700,
      ghostText: brand.M300,
      ghostHover: neutrals.N700,
      dangerBg: danger.D500,
      dangerText: neutrals.N0,
    },
    input: {
      bg: neutrals.N800,
      border: neutrals.N700,
      borderActive: brand.M400,
      borderError: danger.D400,
      text: neutrals.N100,
      placeholder: neutrals.N600,
      disabled: neutrals.N700,
    },
    badge: {
      bg: "rgba(255, 255, 255, 0.1)",
      text: neutrals.N0,
    },
    skeleton: {
      default: neutrals.N700,
    },
  },
};
