import { neutrals, brand, success, warning, danger } from "../basePalette";
import { accent, background, card, cta1, cta1Contrast } from "../colors";
import type { SemanticColors } from "../semanticColors";

export const lightColors: SemanticColors = {
  text: {
    heading: neutrals.N900,
    body: neutrals.N800,
    caption: neutrals.N500,
    brand: brand.M700,
    subtle: neutrals.N600,
    subtlest: neutrals.N400,
    disabled: neutrals.N400,
    success: success.S700,
    successMid: success.S600,
    successContrast: success.S50,
    warning: warning.W700,
    warningMid: warning.W600,
    warningContrast: warning.W50,
    danger: danger.D700,
    dangerContrast: danger.D50,
    linkDefault: brand.M600,
    linkHover: brand.M700,
    linkPressed: brand.M800,
    negative: danger.D600,
  },
  icon: {
    default: neutrals.N600,
    brand: brand.M600,
    subtle: neutrals.N500,
    subtlest: neutrals.N400,
    disabled: neutrals.N400,
    success: success.S600,
    successMid: success.S500,
    successContrast: success.S400,
    warning: warning.W600,
    warningMid: warning.W500,
    warningContrast: warning.W400,
    danger: danger.D600,
    dangerContrast: danger.D500,
    linkDefault: brand.M600,
    linkHover: brand.M700,
    linkPressed: brand.M800,
    negative: danger.D600,
  },
  border: {
    default: neutrals.N200,
    subtle: neutrals.N300,
    subtlest: neutrals.N100,
    light: neutrals.N100,
    lightest: neutrals.N50,
    brand: brand.M500,
    brandLight: brand.M300,
    brandLighter: brand.M100,
    brandContrast: brand.M800,
    focus: brand.M500,
    error: danger.D500,
    success: success.S500,
    warning: warning.W500,
    danger: danger.D500,
  },
  surface: {
    // Fondo de pantalla = background.default (beige de marca).
    pageDefault: background.default,
    pageSubtlest: neutrals.N50,
    pageSubtle: neutrals.N100,
    // Tarjetas sobre background.default = card.background.
    card: card.background,
    cardBorder: background.default,
    brand: brand.M500,
    brandSubtle: brand.M100,
    brandSubtler: brand.M50,
    brandSubtlest: brand.M50,
    success: success.S500,
    successSubtle: success.S50,
    warning: warning.W500,
    warningSubtle: warning.W50,
    danger: danger.D500,
    dangerSubtle: danger.D50,
    overlay: neutrals.N900,
    modal: neutrals.N0,
  },
  components: {
    // Sidebar = superficie oscura de marca (accent). Íconos/textos solo accent.*.
    // Item activo = CTA1 con texto `cta1Contrast` encima.
    sidebar: {
      background: accent.background,
      hover: "rgba(255, 255, 255, 0.05)",
      activeBackground: cta1,
      activeText: cta1Contrast,
      text: accent.text.secondary,
      sectionTitle: accent.text.secondary,
      title: accent.text.primary,
    },
    button: {
      primaryBg: brand.M500,
      primaryText: neutrals.N0,
      primaryHover: brand.M600,
      primaryPressed: brand.M700,
      primaryDisabled: neutrals.N300,
      secondaryBg: neutrals.N0,
      secondaryText: brand.M600,
      secondaryBorder: brand.M500,
      secondaryHover: brand.M50,
      ghostText: brand.M600,
      ghostHover: brand.M50,
      dangerBg: danger.D500,
      dangerText: neutrals.N0,
    },
    input: {
      bg: neutrals.N0,
      border: neutrals.N200,
      borderActive: brand.M500,
      borderError: danger.D500,
      text: neutrals.N900,
      placeholder: neutrals.N400,
      disabled: neutrals.N100,
    },
    badge: {
      bg: "rgba(255, 255, 255, 0.1)",
      text: neutrals.N0,
    },
    skeleton: {
      default: neutrals.N200,
    },
  },
};
